"""slug e imagen para marca

Revision ID: f76551d165db
Revises: 6b81d641cb1e
Create Date: 2018-11-25 19:00:06.043509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f76551d165db'
down_revision = '6b81d641cb1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marcas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagen', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('slug', sa.String(length=100), nullable=False))
        batch_op.create_unique_constraint(None, ['slug'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marcas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('slug')
        batch_op.drop_column('imagen')

    # ### end Alembic commands ###
